CREATE EVENT archive_old_orders
ON SCHEDULE EVERY 1 HOUR
STARTS '2024-06-16 21:21:41.000'
ON COMPLETION NOT PRESERVE
ENABLE
DO BEGIN
    DECLARE item_count INT;

    
    SELECT COUNT(*)
    INTO item_count
    FROM ORDERS
    WHERE DATE < CURDATE() - INTERVAL 40 DAY
      AND ARCHIVE != 'X';

    
    IF item_count > 0 THEN
        
        INSERT INTO `ORDER_HISTORY` (ORDER_ID, ORDER_OWNER_ID, ORDER_QUANTITY, ORDER_AMOUNT, DESCRIPTION, DATE)
        SELECT ORDER_ID, ORDER_OWNER_ID, ORDER_QUANTITY, ORDER_AMOUNT, DESCRIPTION, DATE
        FROM ORDERS
        WHERE DATE < CURDATE() - INTERVAL 40 DAY
          AND ARCHIVE != 'X';

        
        UPDATE `ORDERS` o
        SET o.`ARCHIVE` = 'X'
        WHERE DATE < CURDATE() - INTERVAL 40 DAY
          AND o.`ARCHIVE` != 'X';

        
        UPDATE ORDER_ITEMS oi
        JOIN `ORDERS` o ON oi.ORDER_ID = o.ORDER_ID
        SET oi.ARCHIVE = 'X'
        WHERE DATE < CURDATE() - INTERVAL 40 DAY
          AND oi.ARCHIVE != 'X';
    END IF;
END;