USE buyhub;

-- Requirement 1
CREATE INDEX r1_pdt_supid ON PRODUCT (SUPPLIER_ID);
CREATE INDEX r1_pdt_spid ON SUPPLIER (SUPPLIER_ID);

-- Requirement 2
CREATE INDEX r2_itm_pid ON ORDER_ITEMS (PRODUCT_ID);
CREATE INDEX r2_pdt_spid ON PRODUCT (SUPPLIER_ID);
CREATE INDEX r2_itm_spid ON ORDER_ITEMS (SUPPLIER_ID);

-- Requirement 3
CREATE INDEX r3_od_cusid  ON ORDERS (ORDER_OWNER_ID);
CREATE INDEX r3_cusid ON CUSTOMER (CUSTOMER_ID);


-- Requirement 4
CREATE INDEX r4_od_itmid ON ORDER_ITEMS (ORDER_ITEMS_ID);
CREATE INDEX r4_rtn_od_itmid ON `RETURN` (ORDER_ITEMS_ID);

-- Requirement 5
CREATE INDEX r5_pd_caid ON PRODUCT (CATEGORY_ID);
CREATE INDEX r5_catid ON CATEGORY (CATEGORY_ID);
CREATE INDEX r5_od_dt ON ORDERS (`DATE`);
CREATE INDEX r5_od_itm_pdid_2 ON ORDER_ITEMS (PRODUCT_ID);