/*According to the business request, these are the following queries:*/


/*
 * 1. Detail information about suppliers and the number of products that they provide.
 */
SELECT s.SUPPLIER_NAME, s.EMAIL, s.PHONE_NO, 
COUNT(p.PRODUCT_ID) AS PRODUCT_COUNT
FROM SUPPLIER s 
JOIN PRODUCT p ON s.SUPPLIER_ID =p.SUPPLIER_ID 
GROUP BY s.SUPPLIER_ID ,s.SUPPLIER_NAME ,s.EMAIL ,s.PHONE_NO 

/* 2. 10 best-selling products with the total amount and their supplier. */
select * from PRODUCT p ;
SELECT * FROM ORDER_ITEMS oi LIMIT 10;

SELECT 
	p.PRODUCT_ID ,
	  p.PRODUCT_NAME 
	, p.SUPPLIER_ID 
	, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM ORDER_ITEMS AS ITM
JOIN PRODUCT p ON ITM.PRODUCT_ID =p.PRODUCT_ID 
JOIN SUPPLIER s ON ITM.SUPPLIER_ID =s.SUPPLIER_ID 
GROUP BY p.PRODUCT_NAME ,s.SUPPLIER_NAME 
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10;

SELECT * FROM ORDER_ITEMS oi;


# 3. List of customers and their total purchases.

SELECT 
	 CTM.FIRST_NAME AS CUSTOMER
	,SUM(ORD.ORDER_AMOUNT) AS TOTAL_PURCHASES 
FROM CUSTOMER AS CTM
LEFT JOIN ORDERS ORD 
	ON CTM.CUSTOMER_ID = ORD.ORDER_OWNER_ID
GROUP BY CUSTOMER_ID ;

/* 4. List of returned items.*/
SELECT * FROM `RETURN`c ;

/* 5. List of products in the fashion category that were sold last month.*/

SELECT p.PRODUCT_ID ,p.PRODUCT_NAME,c.CATEGORY_NAME
FROM CATEGORY c 
JOIN PRODUCT p ON p.CATEGORY_ID =c.CATEGORY_ID 
JOIN ORDER_ITEMS oi ON oi.PRODUCT_ID =c.CATEGORY_ID
JOIN ORDERS o ON o.ORDER_ID =p.PRODUCT_ID
WHERE CATEGORY_NAME ='FASHION' AND o.DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 1 MONTH) AND CURDATE();




